# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.10
_src_path: gh:npikall/py-bootstrap
author_email: nikolas.pikall@gmail.com
author_fullname: Nikolas Pikall
author_username: npikall
ci_github: true
ci_gitlab: false
copyright_license: None
include_docs: false
pre_commit: prek
project_name: eo-toolbox
repo_name: eo_toolbox
use_goreleaser: false
