from typing import Any, Protocol

# ruff: noqa: ANN401


class SupportsMathOps[T](Protocol):
    """Protocol that supports mathematical operations."""

    def __sub__(self, other: Any) -> T: ...
    def __rsub__(self, other: Any) -> T: ...
    def __add__(self, other: Any) -> T: ...
    def __radd__(self, other: Any) -> T: ...
    def __truediv__(self, other: Any) -> T: ...
    def __rtruediv__(self, other: Any) -> T: ...
    def __mul__(self, other: Any) -> T: ...
    def __rmul__(self, other: Any) -> T: ...
